# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: So Much For Subtlety
description: > # this means to ignore newlines until "baseurl:"
  So Much For Subtlety is a series of random conversations, thought experiments and environmental rants between <a href="http://www.twitter.com/Josh_Harrington">Josh Harrington</a> and <a href="http://www.twitter.com/samlester">Sam Lester</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.somuchfor.com" # the base hostname & protocol for your site
email: "somuchforpodcast@gmail.com"
author: "Sam Lester and Josh Harrington"
twitter_username: smfspodcast
permalink: /:title

# Build settings
markdown: kramdown
